
port: 5002

# this line below hides the banner on the homepage. Github pages always overrides this to 'true' so we can tell
# when we are deploying the site there vs a local machine
safe: false

timezone: America/New_York

url: https://beta.covideducationrecovery.global
baseurl: /

# Site settings
title: COVID-19 Global Education Recovery Tracker 
email: help@covideducationrecovery.global
description: "Monitoring the impact of the COVID-19 pandemic on response and recovery for students across the globe, by Johns Hopkins University, the World Bank, and UNICEF."
image: img/og-image.png

# Collection Settings

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      libraries:
     
     

collections:
  - faqs
  - news

# Build settings
markdown: kramdown
permalink: /stories/:year-:month-:day-:slug/

# paginate: 5
# paginate_path: "/stories/page:num/"