
name: transfer-imf-who-vaccine-supply-data
on:
  workflow_dispatch:

jobs:
  get-v2-data:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COVID }}
          
      - run: git config --global user.email "beta@covideducationrecovery.global"
      - run: git config --global user.name "Automated Survey V2-Data"

      - name: download latest file
        run: | 
          CURRENTDATESTRING=$(date +"%Y-%m-%d")
          NEWFILENAME="data/imf-who/imf-who-vaccine-supply-tracker-${CURRENTDATESTRING}.xlsx"
          STATUS=$(curl -s -S -o ${NEWFILENAME} -w '%{http_code}' "https://www.imf.org/en/Topics/imf-and-covid19/-/media/Files/Topics/COVID/IMF-WHO/imf-who-covid-19-vaccine-supply-tracker.ashx")
          if [ $STATUS -eq 200 ]; then
            echo "downloaded file"
          else
            echo "error code $STATUS downloading file"
            rm -rf ${NEWFILENAME}
            exit 1
          fi

      - name: add latest file for commit
        run: git add ${NEWFILENAME}

      - name: commit changes
        run: git commit -m "automated V2-Data update"

      - name: Push changes
        run: git push
